import Head from 'next/head'
import styles from 'styles/index.module.css'
import { useRouter } from 'next/router'
import {Grid, Card, Text } from '@nextui-org/react'

export default function Home() {
  const router = useRouter()

  const handleCardClick = function(url:string){
    router.push({
      pathname: url
    })
  }

  return (
    <div className={styles.body}>
      <Head>
        <title>Welcome to UES Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{margin: '50px'}}>
        <Text b size="$5xl">
          Welcome to UES Connect
        </Text>
      </div>
      <Grid.Container justify={"center"} gap={0} md css={{height: '100%'}}>
        <Grid css={{width: '40%', height: '100%'}}>
          <Card isHoverable isPressable
                css={{ h: "80%", $$cardColor: '#EBECF0', borderRadius: 0, justifyContent: 'center', alignItems: 'center'}}
                onPress={() => handleCardClick('/student-view/student-landing')}
          >
            <Card.Body>
              <Text b size='$3xl' color={'black'}>
                I'm A Student...
              </Text>
              <Text size='$xl' color={'black'}>
                Browse club position postings and submit your application!
              </Text>
            </Card.Body>
          </Card>
        </Grid>
        <Grid css={{width: '40%', height: '100%'}}>
          <Card isHoverable isPressable
                css={{ h: "80%", $$cardColor: '#01060E', borderRadius: 0, justifyContent: 'center', alignItems: 'center'}}
                onPress={() => handleCardClick('/club-view/sign-in')}
          >
            <Card.Body>
              <Text b size='$3xl' color={'white'}>
                I'm A Club Executive...
              </Text>
              <Text size='$xl' color={'white'}>
                Login and manage your clubs members and position postings!
              </Text>
            </Card.Body>
          </Card>
        </Grid>
      </Grid.Container>
    </div>

  )
}
