import Head from 'next/head'
import Link from 'next/link'
import styles from 'styles/index.module.css'
import { useTheme } from '@nextui-org/react'
import { CSS, Button } from '@nextui-org/react'

export default function Home() {
  const { theme } = useTheme()
  return (
    <div className={styles.body}>
      <Head>
        <title>Welcome to UES Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.header}>UES Connect</h1>
      <h2 className={styles.body}>
        <Link href="/student-view/student-landing">Student View</Link>
        <Link href="/club-view/sign-in">Club View</Link>
      </h2>
    </div>
    
  )
}
